version: '2'

volumes:
    prometheus_data: {}

networks:
  monitor:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16


services:

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
      - 9090:9090
    networks:
      - monitor
    restart: always
#    deploy:
#      placement:
#        constraints:
#          - node.hostname == ${HOSTNAME}


  #alertmanager:
  #  image: prom/alertmanager
  #  ports:
      #- 9093:9093
    #volumes:
      #- ./alertmanager/:/etc/alertmanager/
    #networks:
      #- back-tier
    #restart: always
    #command:
      #- '--config.file=/etc/alertmanager/config.yml'
      #- '--storage.path=/alertmanager'
