{
 "title": "Nacos-Sync",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "nacos-sync monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(system_cpu_usage)" }
   ]
  },
  {
   "title": "task count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "max(nacosSync_task_size)" }
   ]
  },
  {
   "title": "cluster count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "max(nacosSync_cluster_size)" }
   ]
  },
  {
   "title": "load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "max(system_load_average_1m)" },
    {
     "expr": "max(system_load_average_1m{instance=~'$instance'})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "content": "<html><body><center><a href=\"https://nacos.io\"><img src=\"https://nacos.io/img/nacos.png\" style=\"height: 50px;\" ></a></center></body></html>"
  },
  { "title": "alert list", "type": "alertlist", "gridPos": { "h": 16, "w": 6, "x": 18, "y": 4 } },
  {
   "title": "cpu",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "max(system_cpu_usage) * 100" },
    {
     "expr": "max(system_cpu_usage{instance=~'$instance'}) * 100"
    }
   ]
  },
  {
   "title": "memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\",job=\"nacos\"})/sum(jvm_memory_max_bytes{area=\"heap\",job=\"nacos\"}) * 100"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", instance=~'$instance'})/sum(jvm_memory_max_bytes{area=\"heap\", instance=~'$instance'}) * 100"
    }
   ]
  },
  {
   "title": "threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jvm_threads_daemon_threads{job=\"nacos\"})"
    },
    {
     "expr": "max(jvm_threads_daemon{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "gc",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rate(jvm_gc_pause_seconds_count{action=\"end of major GC\",cause=\"Allocation Failure\",job=\"nacos\"}[5m])) * 300"
    },
    {
     "expr": "max(rate(jvm_gc_pause_seconds_count{action=\"end of major GC\"}[5m])) * 300"
    }
   ]
  },
  { "title": "nacos-sync detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "add task rt",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacosSync_add_task_rt_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(nacosSync_add_task_rt_seconds_count{instance=~'$instance'}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "delete task rt",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacosSync_delete_task_rt_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(nacosSync_delete_task_rt_seconds_count{instance=~'$instance'}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "dispatcher task time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacosSync_dispatcher_task_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(nacosSync_dispatcher_task_seconds_count{instance=~'$instance'}[1m])) * 1000"
    }
   ]
  },
  { "title": "nacos-sync alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "cpu alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(system_cpu_usage) * 100" }
   ]
  },
  {
   "title": "load  alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(system_load_average_1m)" }
   ]
  },
  {
   "title": "memory alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})/sum(jvm_memory_max_bytes{area=\"heap\"}) * 100"
    }
   ]
  },
  {
   "title": "threads alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(jvm_threads_daemon)" }
   ]
  },
  {
   "title": "gc alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(jvm_gc_pause_seconds_count{action=\"end of major GC\"}[5m])) * 300"
    }
   ]
  },
  {
   "title": "sync task error alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacosSync_sync_task_error_total[1m])) * 60"
    }
   ]
  }
 ]
}